# All available hooks: https://pre-commit.com/hooks.html or here https://lorenzwalthert.github.io/precommit/articles/available-hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.0
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
    -   id: parsable-R
#    -   id: lintr


