---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# werptoolkitr

<!-- badges: start -->
<!-- badges: end -->

The goal of werptoolkitr is to ...

## Installation

You can install the development version of werptoolkitr from [GitHub](https://github.com/) with `devtools::install_github`.
There are a couple extra arguments here than usual because it's a private repo and the R package is a subdirectory. 

The `subdir = 'werptoolkitr'` just tells it the package is in that subdir.

Authorisation can happen a couple ways. No matter what, go to https://github.com/settings/tokens and create a PAT with at least repo scope and copy it. SAVE IT SOMEWHERE OTHER THAN PLAINTEXT. Then, to authorise, the simplest but most dangerous is to use `auth_token = 'YOUR GITHUB PAT'`. 

The better option is to use `credentials::set_github_pat()` to set your PAT using the github signin, which doesn't require you to have it in plaintext. That sets the `GITHUB_PAT` environment variable, which is the default for `auth_token`.  

So, assuming you've created a PAT in github,

``` r
# install.packages("devtools")
credentials::set_github_pat()
devtools::install_github("MDBAuth/WERP_toolkit", subdir = 'werptoolkitr')
```
*IMPORTANT DEV NOTE*
To install from a branch other than "HEAD", use `ref = 'branchname'`. 

## Python dependency
To run, this needs a Python environment containing `py_ewr` (currently 1.0.1). In theory, I have set up the DESCRIPTION file and `.onLoad` to check the environment and build one with that dependency when the package is loaded. But it's not working quite right, and so for now just set up python manually. That should be fine for internal use. This way we can use poetry anyway instead of miniconda. I think I'll be able to sort out the auto-install, but need to do it with a more minimal example. There's a poetry environment in the WERP_toolkit_demo repo that works. 

## Example

Need to include a local example here, high level and linking to vignettes. In the meantime, see the [WERP_toolkit_demo](https://github.com/MDBAuth/WERP_toolkit_demo) for a full demonstration.

