# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, galen_working]
  pull_request:
    branches: [main, master, galen_working]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

        python-version: ["3.11"]

    defaults:
      run:
        shell: bash

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install System Libraries on Ubuntu
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get -y install ssl-cert gdal-bin geos-bin sqlite3 libudunits2-0 make xml2 pandoc librsvg2-2

      - name: Install Dependencies on macOS
        if: matrix.config.os == 'macos-latest'
        run: |
          brew install geos gdal proj

      - name: Set-up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-pip-wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Check dependencies
        run: poetry show

      # - name: Set up R
      #   uses: r-lib/actions/setup-r@v2
      #   with:
      #     r-version: ${{ matrix.config.r }}
      #     http-user-agent: ${{ matrix.config.http-user-agent }}
      #     use-public-rspm: true
      #
      # - name: Install R dependencies
      #   uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     extra-packages: any::rcmdcheck
      #     needs: check
      #
      # - name: Run R CMD check
      #   uses: r-lib/actions/check-r-package@v2
      #   with:
      #     upload-snapshots: true
